steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
      ]
    dir: tugas2/frontend_web  # agar app.yaml bisa dibaca

timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY