###
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "mantap",
    "email": "mantap@example.com",
    "password": "12345678910"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mantap@example.com",
    "password": "12345678910"
}

###
GET http://localhost:5000/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJtYW50YXAiLCJpYXQiOjE3NDE4MTQzNjQsImV4cCI6MTc0MTgxNzk2NH0._VxhQdnc6Iu1lRa8tvvx23Wizh4BS1mwgmWgUy1GrIc

###
POST http://localhost:5000/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJtYW50YXAiLCJpYXQiOjE3NDE4MTQzNjQsImV4cCI6MTc0MTgxNzk2NH0._VxhQdnc6Iu1lRa8tvvx23Wizh4BS1mwgmWgUy1GrIc

{
    "title": "testing notes",
    "content": "[ORIGINAL] gacor kang"
}

###
PUT http://localhost:5000/notes/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJtYW50YXAiLCJpYXQiOjE3NDE4MTQzNjQsImV4cCI6MTc0MTgxNzk2NH0._VxhQdnc6Iu1lRa8tvvx23Wizh4BS1mwgmWgUy1GrIc

{
    "title": "testing notes updated",
    "content": "[PART-1] testing notes mantap"
}

###
DELETE http://localhost:5000/notes/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJtYW50YXAiLCJpYXQiOjE3NDE4MTQzNjQsImV4cCI6MTc0MTgxNzk2NH0._VxhQdnc6Iu1lRa8tvvx23Wizh4BS1mwgmWgUy1GrIc

###
GET http://localhost:5000/notes/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwidXNlcm5hbWUiOiJtYW50YXAiLCJpYXQiOjE3NDE4MTQzNjQsImV4cCI6MTc0MTgxNzk2NH0._VxhQdnc6Iu1lRa8tvvx23Wizh4BS1mwgmWgUy1GrIc